apiVersion: apps/v1
kind: Deployment
metadata:
  name: bingo-multi
  labels:
    tags.datadoghq.com/env: "prod"
    tags.datadoghq.com/service: "bingo-multi"
    tags.datadoghq.com/version: "1.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bingo-multi
  template:
    metadata:
      labels:
        app: bingo-multi
    spec:
      containers:
        - name: bingo-multi
          image: localhost:32000/bingo-multi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DD_ENV
              value: "prod"
            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: REDIS_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: REDIS_PORT
              value: "30010"


---
apiVersion: v1
kind: Service
metadata:
  name: bingo-multi
spec:
  selector:
    app: bingo-multi
  ports:
    - name: http
      protocol: TCP
      port: 3000
      nodePort: 30017
  type: LoadBalancer



